services:

  laravel-php:
    build: ./php
    container_name: LaravelPHP
    volumes:
      - ../../apps/laravel:/var/www/html
      - ./.env:/var/www/html/.env
    working_dir: /var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=laravel
      - XDEBUG_CONFIG=client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003"
    networks:
      - MyTransportNetwork

  laravel-nginx:
    image: nginx:alpine
    container_name: LaravelNginx
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ../../apps/laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - laravel-php
    networks:
      - MyTransportNetwork

networks:
  MyTransportNetwork:
    external: true
